### ISSUE TITLE
pip install google : ImportError: cannot import name IncompleteRead

### ISSUE THREAD

**Issue by SaiGonSeamus** [opsdisk/pagodo#3]
Any idea on this?

root@DS:~# pip install google
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by opsdisk** [comment]
Haven't seen that one before.  I'd try running "pip install -r requirements.txt" first.  If that fails, reinstall pip.

**Comment by SaiGonSeamus** [comment]
Tried both of those, neither worked.

**Comment by opsdisk** [comment]
Looks like you're running as root based the shell prompt.  Is that correct?  I'd try installing another package via pip and see if you get something similar.  Besides that, don't know what else to recommend.

**Comment by SaiGonSeamus** [comment]
It's a debian jessie thing. it's working now.

**Comment by opsdisk** [comment]
Glad to hear you figured it out!
